services:
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: phonestore-database
    environment:
      POSTGRES_DB: phonestore_db
      POSTGRES_USER: phonestore_user
      POSTGRES_PASSWORD: password
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432" # Changed from 5432 to 5433 to avoid potential conflicts
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "phonestore_db", "-U", "phonestore_user"]
      timeout: 5s
      retries: 5
      start_period: 60s

  pgadmin:
    image: dpage/pgadmin4
    container_name: phonestore-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@phonestore.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80" # Changed from 8080 to 8081 to avoid potential conflicts
    depends_on:
      - database

  mailer:
    image: axllent/mailpit
    container_name: phonestore-mailer
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

volumes:
  database_data:
